AWSTemplateFormatVersion: '2010-09-09'
Description: >
  CodePipeline for deploying sns-relate-aws stack from GitHub (Tokyo region)
  to Osaka region (ap-northeast-3).

Resources:
  SNSRelatePipelineRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: sns-relate-pipeline-role
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - codepipeline.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AWSCodePipelineFullAccess
        - arn:aws:iam::aws:policy/AWSCloudFormationFullAccess
        - arn:aws:iam::aws:policy/AmazonS3FullAccess

  SNSRelateArtifactBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub "sns-relate-pipeline-artifacts-${AWS::Region}-${AWS::AccountId}"
      VersioningConfiguration:
        Status: Enabled

  SNSRelatePipeline:
    Type: AWS::CodePipeline::Pipeline
    Properties:
      RoleArn: !GetAtt SNSRelatePipelineRole.Arn
      Name: sns-relate-deploy-pipeline
      ArtifactStore:
        Type: S3
        Location: !Ref SNSRelateArtifactBucket
      Stages:
        - Name: Source
          Actions:
            - Name: GitHubSource
              ActionTypeId:
                Category: Source
                Owner: AWS
                Provider: CodeStarSourceConnection
                Version: '1'
              OutputArtifacts:
                - Name: SourceOutput
              Configuration:
                ConnectionArn: arn:aws:codeconnections:ap-northeast-1:071360906030:connection/5ef11dd3-8bcc-42b9-b8bb-f38fb21da91f
                FullRepositoryId: itmaroon/aws-sns-relate
                BranchName: main
        - Name: Build
          Actions:
            - Name: CodeBuild
              ActionTypeId:
                Category: Build
                Owner: AWS
                Provider: CodeBuild
                Version: '1'
              InputArtifacts:
                - Name: SourceOutput
              OutputArtifacts:
                - Name: BuildOutput
              Configuration:
                ProjectName: sns-relate-build
        - Name: Deploy
          Actions:
            - Name: CloudFormationDeploy
              ActionTypeId:
                Category: Deploy
                Owner: AWS
                Provider: CloudFormation
                Version: '1'
              InputArtifacts:
                - Name: BuildOutput
              Configuration:
                ActionMode: CREATE_UPDATE
                StackName: sns-relate-pipeline
                Capabilities: CAPABILITY_NAMED_IAM
                TemplateFile: BuildOutput::template.master.yaml
                Region: ap-northeast-3
                RoleArn: !GetAtt SNSRelatePipelineRole.Arn
      RestartExecutionOnUpdate: true

Outputs:
  PipelineName:
    Value: !Ref SNSRelatePipeline
    Description: Name of the created CodePipeline
