# この AWS SAM テンプレートは、関数の設定から生成されました。関数に 1 つ以上のトリガーがある場合は、これらのトリガーに関連付けられている AWS
# リソースがこのテンプレートで完全に指定されておらず、プレースホルダ値も含まれていないことに注意してください。AWS Infrastructure
# Composer またはお気に入りの IDE でこのテンプレートを開き、他の AWS リソースでサーバーレスアプリケーションを指定するように変更します。
AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: An AWS Serverless Application Model template describing your function.
Resources:
  lambdacleanup:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./src
      Description: >-
        SNS投稿のためS3にアップロードされたファイルを削除する関数。API
        Gateway経由モードとステートマシン制御モードがあり、前者はInsta用変換不要ファイルの削除、後者はInsta用変換ファイルの削除とX用ファイルの削除の機能を有する
      MemorySize: 128
      Timeout: 3
      Handler: lambda_function.lambda_handler
      Runtime: python3.11
      Architectures:
        - x86_64
      EphemeralStorage:
        Size: 512
      Environment:
        Variables:
          IN_BUCKET: itmar-video-upload-bucket
          OUT_BUCKET: itmar-video-converted-bucket
      EventInvokeConfig:
        MaximumEventAgeInSeconds: 21600
        MaximumRetryAttempts: 2
      PackageType: Zip
      Policies:
        - Statement:
            - Effect: Allow
              Action:
                - s3:DeleteObject
                - s3:GetObject
              Resource:
                - arn:aws:s3:::itmar-video-upload-bucket/*
                - arn:aws:s3:::itmar-video-converted-bucket/*
            - Effect: Allow
              Action:
                - dynamodb:DeleteItem
                - dynamodb:GetItem
              Resource: arn:aws:dynamodb:ap-northeast-1:071360906030:table/convert_jobs
            - Effect: Allow
              Action:
                - logs:CreateLogGroup
                - logs:CreateLogStream
                - logs:PutLogEvents
              Resource: '*'
            - Effect: Allow
              Action:
                - logs:CreateLogGroup
              Resource: arn:aws:logs:ap-northeast-1:071360906030:*
            - Effect: Allow
              Action:
                - logs:CreateLogStream
                - logs:PutLogEvents
              Resource:
                - >-
                  arn:aws:logs:ap-northeast-1:071360906030:log-group:/aws/lambda/lambda_cleanup:*
      RecursiveLoop: Terminate
      SnapStart:
        ApplyOn: None
      Events:
        Api1:
          Type: Api
          Properties:
            Path: /MyResource
            Method: ANY
        Api2:
          Type: Api
          Properties:
            Path: /upload
            Method: ANY
      RuntimeManagementConfig:
        UpdateRuntimeOn: Auto
