# この AWS SAM テンプレートは、関数の設定から生成されました。関数に 1 つ以上のトリガーがある場合は、これらのトリガーに関連付けられている AWS
# リソースがこのテンプレートで完全に指定されておらず、プレースホルダ値も含まれていないことに注意してください。AWS Infrastructure
# Composer またはお気に入りの IDE でこのテンプレートを開き、他の AWS リソースでサーバーレスアプリケーションを指定するように変更します。
AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: An AWS Serverless Application Model template describing your function.
Resources:
  lambdastart:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./src
      Description: Xの投稿用情報をconvert-jobに登録し、ステートマシンを起動する。
      MemorySize: 128
      Timeout: 3
      Handler: lambda_function.lambda_handler
      Runtime: python3.11
      Architectures:
        - x86_64
      EphemeralStorage:
        Size: 512
      Environment:
        Variables:
          KMS_KEY_ID: alias/ig-token-key
          STATE_MACHINE_ARN: >-
            arn:aws:states:ap-northeast-1:071360906030:stateMachine:xStateMachine
      EventInvokeConfig:
        MaximumEventAgeInSeconds: 21600
        MaximumRetryAttempts: 2
      PackageType: Zip
      Policies:
        - Statement:
            - Effect: Allow
              Action:
                - dynamodb:GetItem
                - dynamodb:PutItem
                - dynamodb:UpdateItem
                - dynamodb:DescribeTable
              Resource: arn:aws:dynamodb:ap-northeast-1:071360906030:table/convert_jobs
            - Effect: Allow
              Action:
                - states:StartExecution
              Resource: >-
                arn:aws:states:ap-northeast-1:071360906030:stateMachine:xStateMachine
            - Effect: Allow
              Action:
                - kms:Encrypt
                - kms:DescribeKey
              Resource: >-
                arn:aws:kms:ap-northeast-1:071360906030:key/04933e03-887d-4de3-9083-e78d8ea23504
            - Effect: Allow
              Action:
                - logs:CreateLogGroup
              Resource: arn:aws:logs:ap-northeast-1:071360906030:*
            - Effect: Allow
              Action:
                - logs:CreateLogStream
                - logs:PutLogEvents
              Resource:
                - >-
                  arn:aws:logs:ap-northeast-1:071360906030:log-group:/aws/lambda/lambda_start:*
      RecursiveLoop: Terminate
      SnapStart:
        ApplyOn: None
      Events:
        Api1:
          Type: Api
          Properties:
            Path: /x/start_upload
            Method: ANY
      RuntimeManagementConfig:
        UpdateRuntimeOn: Auto
