# この AWS SAM テンプレートは、関数の設定から生成されました。関数に 1 つ以上のトリガーがある場合は、これらのトリガーに関連付けられている AWS
# リソースがこのテンプレートで完全に指定されておらず、プレースホルダ値も含まれていないことに注意してください。AWS Infrastructure
# Composer またはお気に入りの IDE でこのテンプレートを開き、他の AWS リソースでサーバーレスアプリケーションを指定するように変更します。
AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: An AWS Serverless Application Model template describing your function.
Resources:
  lambdagetjobstatus:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./src
      Description: >-
        convert_jobテーブルから指定されたsite_urlをもつ項目を絞り込んで返す。API 
        Gatewayから/jobs?site_url=で呼び出し
      MemorySize: 128
      Timeout: 3
      Handler: lambda_function.lambda_handler
      Runtime: python3.11
      Architectures:
        - x86_64
      EphemeralStorage:
        Size: 512
      EventInvokeConfig:
        MaximumEventAgeInSeconds: 21600
        MaximumRetryAttempts: 2
      PackageType: Zip
      Policies:
        - Statement:
            - Effect: Allow
              Action:
                - dynamodb:Query
                - dynamodb:GetItem
              Resource:
                - >-
                  arn:aws:dynamodb:ap-northeast-1:071360906030:table/convert_jobs
                - >-
                  arn:aws:dynamodb:ap-northeast-1:071360906030:table/convert_jobs/index/wp_id-updated_at-index
                - >-
                  arn:aws:dynamodb:ap-northeast-1:071360906030:table/convert_jobs/index/site_url-updated_at-index
            - Effect: Allow
              Action:
                - logs:CreateLogGroup
              Resource: arn:aws:logs:ap-northeast-1:071360906030:*
            - Effect: Allow
              Action:
                - logs:CreateLogStream
                - logs:PutLogEvents
              Resource:
                - >-
                  arn:aws:logs:ap-northeast-1:071360906030:log-group:/aws/lambda/lambda_get_job_status:*
      RecursiveLoop: Terminate
      SnapStart:
        ApplyOn: None
      Events:
        Api1:
          Type: Api
          Properties:
            Path: /jobs
            Method: ANY
      RuntimeManagementConfig:
        UpdateRuntimeOn: Auto
